import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
  title: "Mogistic | Projects",
  description: "Generated by create next app",
};

const Projects = () => {
  return (
    <div>Projects</div>
  )
}

export default Projects
