// import { GalleryVerticalEnd } from "lucide-react";
import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import Logo from "@/public/images/logo_abstract.png"
import { ArrowLeftFromLine } from "lucide-react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="w-full z-50 bg-gray-50 h-screen fixed top-0 left-0 right-0 bottom-0">
      <div className="grid min-h-svh lg:grid-cols-2">
        <div className="flex flex-col gap-4 p-6 md:p-10">
          <div className="flex justify-between items-center">

              <div className="">
                {/* <GalleryVerticalEnd className="size-4" /> */}
                <Image
                  src={Logo}
                  alt="Mogistic company logo"
                  width={200}
                  height={200}
                  className="h-20 w-auto"
                />
              </div>
            <Link href="/" className="flex items-center gap-2 font-medium">
              <div className="flex gap-3 text-gray-500 hover:text-gray-900">
                <ArrowLeftFromLine />
                Back
              </div>
            </Link>
          </div>
          <div className="flex flex-1 items-center justify-center">
            <div className="w-full max-w-[420px]">
              {children}
            </div>
          </div>
        </div>
        <div className="relative hidden bg-auth_img lg:block bg-cover"/>
      </div>
    </div>
  );
}
