import ContactForm from '@/components/ContactForm'
import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
  title: "Mogistic | Contact",
  description: "Generated by create next app",
};

const Contact = () => {
  return (
    <>
      <ContactForm />
    </>
  )
}

export default Contact
