import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="w-full h-screen fixed top-0 left-0 bg-gray-50 flex bg-background-1 bg-cover z-50">
        <div className="w-8/12 m-auto p-5">
            {children}
        </div>
    </div>
  );
}
